spring:
  # datasource
  datasource:
    url: jdbc:mysql://192.168.88.14:3306/mall_apy?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ${MALL_MYSQL_PASSWORD}

# xxl-job
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:18079/
    executor:
      appname: pay-job-executor
      ip:
      port: 0
      logpath: /Users/yunai/logs/xxl-job/
      logretentiondays: 1
    accessToken:

# rocketmq
rocketmq:
  name-server: 192.168.88.14:9876
  producer:
    group: pay-producer-group
