spring:
  # datasource
  datasource:
    url: jdbc:mysql://180.167.213.26:13306/mall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ${MALL_MYSQL_PASSWORD}

# mybatis
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.iocoder.mall.product.dataobject

# dubbo
dubbo:
  application:
    name: product-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: cn.iocoder.mall.product.service
  provider:
    filter: -exception
    ProductAttrService:
      version: 1.0.0
    ProductCategoryService:
      version: 1.0.0
    ProductSpuService:
      version: 1.0.0
    ProductBrandService:
      version: 1.0.0
    OAuth2Service:
      version: 1.0.0
    ProductSpuCollectionService:
      version: 1.0.0

# rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: product-producer-group

# seata
seata:
  tx-service-group: my_test_tx_group
