spring:
  # datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_admin?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ${MALL_MYSQL_PASSWORD}

# mybatis
#mybatis:
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: cn.iocoder.mall.admin.dataobject

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.iocoder.mall.admin.dataobject

# sms
sms:
  yunPian:
    apiKey:
  aliYun:
    accessKeyId:
    accessSecret:

# dubbo
dubbo:
  application:
    name: admin-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: cn.iocoder.mall.admin.service
  provider:
    filter: -exception
    AdminAccessLogService:
      version: 1.0.0
    AdminService:
      version: 1.0.0
    DataDictService:
      version: 1.0.0
    OAuth2Service:
      version: 1.0.0
    ResourceService:
      version: 1.0.0
    RoleService:
      version: 1.0.0
    SmsService:
      version: 1.0.0

# logging
logging:
  level:
    # dao 开启 debug 模式 mybatis 输入 sql
    cn.iocoder.mall.admin.dao: debug
