spring:
  # datasource
  datasource:
    url: jdbc:mysql://180.167.213.26:13306/mall_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ${MALL_MYSQL_PASSWORD}

# mybatis
#mybatis:
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: cn.iocoder.mall.user.biz.dataobject

# mybatis-plus
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true # 虽然默认为 true ，但是还是显示去指定下。
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: cn.iocoder.mall.user.biz.dataobject
  config-location: classpath:mybatis-config.xml

# dubbo
dubbo:
  application:
    name: user-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: cn.iocoder.mall.user.biz.service
  provider:
    filter: -exception
    MobileCodeService:
      version: 1.0.0
    OAuth2Service:
      version: 1.0.0
    UserAccessLogService:
      version: 1.0.0
    UserAddressService:
      version: 1.0.0
    UserService:
      version: 1.0.0
