spring:
  # datasource
  datasource:
    url: jdbc:mysql://180.167.213.26:13306/mall_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ${MALL_MYSQL_PASSWORD}

  # Spring Cloud 配置项
  cloud:
    nacos:
      # Spring Cloud Nacos Discovery 配置项
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: cn.iocoder.mall.user.biz.dataobject

# Dubbo 配置项
dubbo:
  # Dubbo 注册中心
  registry:
    address: spring-cloud://127.0.0.1:8848 # 指定 Dubbo 服务注册中心的地址
  # Spring Cloud Alibaba Dubbo 专属配置
  cloud:
    subscribed-services: admin-application, product-application # 设置订阅的应用列表，默认为 * 订阅所有应用
  # Dubbo 提供者的协议
  protocol:
    name: dubbo
    port: -1
  # Dubbo 提供服务的扫描基础包
  scan:
    base-packages: cn.iocoder.mall.user.biz.service
  # Dubbo 服务提供者的配置
  provider:
    filter: -exception
    MobileCodeService:
      version: 1.0.0
    UserAccessLogService:
      version: 1.0.0
    UserAddressService:
      version: 1.0.0
    UserService:
      version: 1.0.0
    UserProductSpuCollectionsService:
      version: 1.0.0
  consumer:
    OAuth2Service:
      version: 1.0.0

# rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: user-producer-spu-collection-group
