spring:
  # datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://180.167.213.26:13306/mall_promotion?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ${MALL_MYSQL_PASSWORD}

  # Spring Cloud 配置项
  cloud:
    nacos:
      # Spring Cloud Nacos Discovery 配置项
      discovery:
        server-addr: s1.iocoder.cn:8848 # Nacos 服务器地址

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.iocoder.mall.promotion.biz.dataobject

# Dubbo 配置项
dubbo:
  # Dubbo 注册中心
  registry:
    address: spring-cloud://s1.iocoder.cn:8848 # 指定 Dubbo 服务注册中心的地址
  # Spring Cloud Alibaba Dubbo 专属配置
  cloud:
    subscribed-services: admin-application, product-application # 设置订阅的应用列表，默认为 * 订阅所有应用
  # Dubbo 提供者的协议
  protocol:
    name: dubbo
    port: -1
  # Dubbo 提供服务的扫描基础包
  scan:
    base-packages: cn.iocoder.mall.promotion.biz.service
  consumer:
    ProductSpuService:
      version: 1.0.0
  # Dubbo 服务提供者的配置
  provider:
    filter: -exception
    BannerService:
      version: 1.0.0
    CouponService:
      version: 1.0.0
    ProductRecommendService:
      version: 1.0.0
    PromotionActivityService:
      version: 1.0.0

# Seata 配置项
seata:
  tx-service-group: default # Seata 事务组编号，用于 TC 集群名
  # 服务配置项，对应 ServiceProperties 类
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      default: default
  # Seata 注册中心配置项
  registry:
    type: nacos # 注册中心类型
    nacos:
      serverAddr: ${spring.cloud.nacos.discovery.server-addr} # Nacos 服务地址
      namespace: # Nacos 命名空间
      cluster: default # 使用的 Seata 分组

# logging
logging:
  level:
    cn.iocoder.mall.promotion.dao: debug
